In [ ]:
import json
import pandas as pd
import re
with open('fake_news.json') as f:
  fake_news = json.load(f)
  #json to dataframe
  fake_news = pd.json_normalize(fake_news,'fake_news')
  f.close()

with open('true_news.json') as f:
  true_news = json.load(f)
  #json to dataframe
  true_news = pd.json_normalize(true_news,'true_news')
  f.close()

In [ ]:
true_news = true_news.rename(columns={'short_desc': 'short_description'})

In [ ]:
true_news=true_news.drop(['name','url'],axis=1)
fake_news=fake_news.drop(['url'],axis=1)

In [ ]:

true_news=true_news.drop(['full_title','long_description',],axis=1)
fake_news=fake_news.drop(['full_title', 'long_description'],axis=1)

In [ ]:
pd.set_option('display.max_colwidth', None)

In [ ]:
fake_news=fake_news.dropna()
true_news=true_news.dropna()
true_news

                                                                                                                                                                          short_description
0                                                भारत ने ऑस्ट्रेलिया में टेस्ट सिरीज़ में ऐतिहासिक जीत दर्ज की. चौथे और निर्णायक मैच में नौजवान गेंदबाज़ मोहम्मद सिराज ने अहम भूमिका निभाई.
1                 ब्रिस्बेन टेस्ट में भारत की दीवार कहे जाने वाले चेतेश्वर पुजारा ने अर्धशतक जमाया. पारी के दौरान वो चोटिल भी हुए और ऑस्ट्रेलियाई गेंदबाज़ों की कई गेंदे उनके शरीर पर लगीं.
2                                                                    पाकिस्तानी टीवी प्रेजेंटर सैय्यद इक़रारुल हसन अपने कुछ ट्वीट के कारण निशाने पर आ गए. उन्हें देशद्रोही तक कहा जाने लगा.
3                                                                    किसी से पूछा जाए कि दिल्ली में पहली गणतंत्र दिवस परेड कहां हुई थी तो इसका जवाब वो राजपथ ही देगा, लेकिन यह सही नहीं है.
4                                                                                                                                      वेब सिरीज़ तांडव को लेकर जारी विवाद पर आज का कार्टून
..                                                                                                                                                                                      ...
887                                                                                          चालक ने कार रोकने के बजाय उसे चलाना जारी रखा. और एक ट्रैफ़िक पुलिसकर्मी कार के बॉनेट पर आ गया.
888                                                                                                                                       ये मिसाइल 400 किलोमीटर से ज़्यादा मार कर सकती है.
889                                      आकर्षण का केंद्र वो शक्तिशाली पहलवान होते थे, जिनका संबंध प्रसिद्ध भोलू पहलवान परिवार से था. दारुल सेहत को सब 'भोलू का अखाड़ा' के नाम से जानते थे.
890  बिहार के जातिगत समीकरणों की बात बहुत होती है, लेकिन लंबे समय से बीजेपी हिंदू पहचान के आधार पर वोटरों को लामबंद करने में लगी है, इसके साथ ही सोशल इंजीनियरिंग पर भी उसका ध्यान रहता है.
891                                                                                                  एनआईए ने 83 साल के फ़ादर स्टेन स्वामी को गिरफ़्तार कर उन पर यूएपीए की धाराएँ लगाई हैं.

[760 rows x 1 columns]

In [ ]:
#Removing Seperators

def remove_sep( news ):
 for i in list(true_news):
  news[i]=news[i].str.replace('|', '')
  news[i]=news[i].str.replace('?', '')
  news[i]=news[i].str.replace(':', '')
  news[i]=news[i].str.replace(';', '')
  news[i]=news[i].str.replace("'", '')
  news[i]=news[i].str.replace('"', '')
  news[i]=news[i].str.replace(',', '')
  news[i]=news[i].str.replace('.', '')
  news[i]=news[i].str.replace('(', '')
  news[i]=news[i].str.replace(')', '')
  news[i]=news[i].str.replace('\n', '')
  news[i]=news[i].str.replace('&', '')
  news[i]=news[i].str.replace('।', '')
  

remove_sep(true_news)
remove_sep(fake_news)

<ipython-input-32-c3f31a6d38a2>:5: FutureWarning: The default value of regex will change from True to False in a future version. In addition, single character regular expressions will *not* be treated as literal strings when regex=True.
  news[i]=news[i].str.replace('|', '')
<ipython-input-32-c3f31a6d38a2>:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  news[i]=news[i].str.replace('|', '')
<ipython-input-32-c3f31a6d38a2>:6: FutureWarning: The default value of regex will change from True to False in a future version. In addition, single character regular expressions will *not* be treated as literal strings when regex=True.
  news[i]=news[i].str.replace('?', '')
<ipython-input-32-c3f31a6d38a2>:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  news[i]=news[i].str.replace('?', '')
<ipython-input-32-c3f31a6d38a2>:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  news[i]=news[i].str.replace(':', '')
<ipython-input-32-c3f31a6d38a2>:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  news[i]=news[i].str.replace(';', '')
<ipython-input-32-c3f31a6d38a2>:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  news[i]=news[i].str.replace("'", '')
<ipython-input-32-c3f31a6d38a2>:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  news[i]=news[i].str.replace('"', '')
<ipython-input-32-c3f31a6d38a2>:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  news[i]=news[i].str.replace(',', '')
<ipython-input-32-c3f31a6d38a2>:12: FutureWarning: The default value of regex will change from True to False in a future version. In addition, single character regular expressions will *not* be treated as literal strings when regex=True.
  news[i]=news[i].str.replace('.', '')
<ipython-input-32-c3f31a6d38a2>:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  news[i]=news[i].str.replace('.', '')
<ipython-input-32-c3f31a6d38a2>:13: FutureWarning: The default value of regex will change from True to False in a future version. In addition, single character regular expressions will *not* be treated as literal strings when regex=True.
  news[i]=news[i].str.replace('(', '')
<ipython-input-32-c3f31a6d38a2>:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  news[i]=news[i].str.replace('(', '')
<ipython-input-32-c3f31a6d38a2>:14: FutureWarning: The default value of regex will change from True to False in a future version. In addition, single character regular expressions will *not* be treated as literal strings when regex=True.
  news[i]=news[i].str.replace(')', '')
<ipython-input-32-c3f31a6d38a2>:14: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  news[i]=news[i].str.replace(')', '')
<ipython-input-32-c3f31a6d38a2>:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  news[i]=news[i].str.replace('\n', '')
<ipython-input-32-c3f31a6d38a2>:16: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  news[i]=news[i].str.replace('&', '')
<ipython-input-32-c3f31a6d38a2>:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  news[i]=news[i].str.replace('।', '')

In [ ]:
#Stemming
suffixes = {
    # 1: ["ो", "े", "ू", "ु", "ी", "ि", "ा"],
    1: ["कर", "ाओ", "िए", "ाई", "ाए", "ने", "नी", "ना", "ते", "ीं", "ती", "ता", "ाँ", "ां", "ों", "ें"],
    2: ["ाकर", "ाइए", "ाईं", "ाया", "ेगी", "ेगा", "ोगी", "ोगे", "ाने", "ाना", "ाते", "ाती", "ाता", "तीं", "ाओं", "ाएं", "ुओं", "ुएं", "ुआं"],
    3: ["ाएगी", "ाएगा", "ाओगी", "ाओगे", "एंगी", "ेंगी", "एंगे", "ेंगे", "ूंगी", "ूंगा", "ातीं", "नाओं", "नाएं", "ताओं", "ताएं", "ियाँ", "ियों", "ियां"],
    4: ["ाएंगी", "ाएंगे", "ाऊंगी", "ाऊंगा", "ाइयाँ", "ाइयों", "ाइयां"],
}

def hi_stem(word):
    for L in  4, 3, 2, 1:
        if len(word) > L + 1:
            for suf in suffixes[L]:
                if word.endswith(suf):
                    return word[:-L]
    return word

In [ ]:
id1=list(fake_news.index)
id2=list(true_news.index)

In [ ]:
str_temp=""
count=0
for i in list(fake_news):
  count=0
  for j in list(fake_news[i]):
    for words in j.split():
      str_temp+=hi_stem(words)
      str_temp+=" "
    fake_news.loc[id1[count],i]=str_temp
    str_temp=""
    count+=1

In [ ]:
str_temp=""
count=0
for i in list(true_news):
  count=0
  for j in list(true_news[i]):
    for words in j.split():
      str_temp+=hi_stem(words)
      str_temp+=" "
    true_news.loc[id2[count],i]=str_temp
    str_temp=""
    count+=1

In [ ]:
true_news

                                                                                                                                                                  short_description
0                                             भारत ने ऑस्ट्रेलिया मे टेस्ट सिरीज़ मे ऐतिहासिक जीत दर्ज की चौथे और निर्णायक मैच मे नौजवान गेंदबाज़ मोहम्मद सिराज ने अहम भूमिका निभा
1                  ब्रिस्बेन टेस्ट मे भारत की दीवार कहे जा वाले चेतेश्वर पुजारा ने अर्धशतक जमा पारी के दौरान वो चोटिल भी हुए और ऑस्ट्रेलिया गेंदबाज़ो की कई गेंदे उनके शरीर पर लगी
2                                                                    पाकिस्तान टीवी प्रेजेंटर सैय्यद इक़रारुल हसन अपन कुछ ट्वीट के कारण निशा पर आ गए उन्हे देशद्रोही तक कहा जा लगा
3                                                                   किसी से पूछा जा कि दिल्ली मे पहली गणतंत्र दिवस परेड कहा हुई थी तो इसका जवाब वो राजपथ ही दे लेकिन यह सही नही है
4                                                                                                                              वेब सिरीज़ तांडव को लेक जारी विवाद पर आज का कार्टून
..                                                                                                                                                                              ...
887                                                                                      चालक ने कार रोकन के बजाय उसे चला जारी रखा और एक ट्रैफ़िक पुलिसकर्मी कार के बॉनेट पर आ गया
888                                                                                                                                ये मिसाइल 400 किलोमीटर से ज़्यादा मार कर सकत है
889                                    आकर्षण का केंद्र वो शक्तिशाली पहलवान होत थे जिनका संबंध प्रसिद्ध भोलू पहलवान परिवार से था दारुल सेहत को सब भोलू का अखाड़ा के नाम से जानत थे
890  बिहार के जातिगत समीकरणो की बात बहुत होत है लेकिन लंबे समय से बीजेपी हिंदू पहचान के आधार पर वोटरो को लामबंद करन मे लगी है इसके साथ ही सोशल इंजीनियरिंग पर भी उसका ध्यान रहत है
891                                                                                           एनआईए ने 83 साल के फ़ादर स्टेन स्वामी को गिरफ़्तार कर उन पर यूएपीए की धाराएँ लगा हैं

[760 rows x 1 columns]